template-file-path: security-baseline-level1.yaml

stack-name: bem11-security-baseline-lab

region: us-east-1

capabilities:
  - CAPABILITY_IAM
  - CAPABILITY_NAMED_IAM

parameters:
  FullName: "TimothyNlenjibi"

tags:
  Project: BEM11-Security-Baseline-Lab
  Environment: Lab
  ManagedBy: GitSync-CloudFormation
  ControlLevel: Level1-IAM-Secrets