template-file-path: vpc-lab.yaml

stack-name: bem11-vpc-lab

region: us-east-1

capabilities:
  - CAPABILITY_IAM
  - CAPABILITY_NAMED_IAM

parameters:
  StudentName: "Timothy Nlenjibi"
  LabName: "BEM11 Lab"
  InstanceType: t3.micro

tags:
  Project: BEM11-Networking-Lab
  Environment: Lab
  ManagedBy: GitSync-CloudFormation